AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DeploymentStage:
    Type: String
    Default: stage
    AllowedValues:
      - stage
      - prod
    Description: Stage to deploy to (stage or prod)
  
  LogLevel:
    Type: String
    Default: info
    AllowedValues:
      - debug
      - info
      - warn
      - error
    Description: Minimum log level for log messages

Globals:
  Function:
    MemorySize: 128
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5
    Environment:
      Variables:
        STAGE: !Ref DeploymentStage
        LOG_LEVEL: !Ref LogLevel

Resources:
  HttpApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref DeploymentStage

  Ping:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/lemma_ping/
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/ping'
            Method: get
            RestApiId: !Ref HttpApi
