AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LemmaDevPingFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/lambda/lemma-dev-ping/
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/ping'
            Method: get

Outputs:
  FunctionName:
    Value: !Ref LemmaDevPingFunction
    Description: Name of the function.
