AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LemmaPingFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/lambda/lemma_ping/
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/ping'
            Method: get

Outputs:
  FunctionName:
    Value: !Ref LemmaPingFunction
    Description: Function name of lambda function 'lemma_ping'
